#!/bin/bash

# image name should be passed as arg, along with W/M tag for OS
if [ "$#" -ne 1 ]; then
  echo "Usage: RunDocker <image_name>"
  exit
else
  # parse args
  export IMG_NAME="$1"
fi

#export OSTYPE="darwin17"

# set appropriate paths based on OS
if [[ "$OSTYPE" == "msys" ]]; then
  # windows
  export SQUEEZE_DATA="N:/Squeezebox"
  export MUSIC_DIR="M:/Music"
elif [[ "$OSTYPE" =~ ^darwin.* ]]; then
  # mac
  export SQUEEZE_DATA="/Volumes/Data/Squeezebox"
  export MUSIC_DIR="/Volumes/Multimedia/Music"
else
  echo "OS flag script doesn't know, exiting now"
  exit
fi

# some debug output
echo "Running image: ${IMG_NAME}"
echo "SQUEEZE_DATA: ${SQUEEZE_DATA}"
echo "MUSIC_DIR: ${MUSIC_DIR}"


# start LMS Docker container
docker run -d --init \
           -p 9000:9000 \
           -p 9090:9090 \
           -p 3483:3483 \
           -p 3483:3483/udp \
           -v ${SQUEEZE_DATA}:/srv/squeezebox \
           -v ${MUSIC_DIR}:/srv/music \
           ${IMG_NAME}

#          -v /etc/localtime:/etc/localtime:ro \
