#!/bin/bash

# image name should be passed as arg, along with W/M tag for OS
if [ "$#" -ne 2 ]; then
  echo "Usage: RunDocker <image_name> <W/M>"
  exit
else
  # parse args
  export IMG_NAME="$1"
  export OS_FLAG="$2" 
fi

# set appropriate paths based on OS
if [ "$OS_FLAG" == "W" ] || [ "$OS_FLAG" == "w" ]; then
  # windows
  export SQUEEZE_DATA="N:/Squeezebox"
  export MUSIC_DIR="M:/Music"
elif [ "$OS_FLAG" == "M" ] || [ "$OS_FLAG" == "m" ]; then
  # mac
  export SQUEEZE_DATA="/Volumes/Data/Squeezebox"
  export MUSIC_DIR="/Volumes/Multimedia/Music"
else
  echo "Invalid OS flag, exiting"
  exit
fi

# some debug output
echo "Running image: ${IMG_NAME}"
echo "SQUEEZE_DATA: ${SQUEEZE_DATA}"
echo "MUSIC_DIR: ${MUSIC_DIR}"


# start LMS Docker container
docker run -d --init \
           -p 9000:9000 \
           -p 9090:9090 \
           -p 3483:3483 \
           -p 3483:3483/udp \
           -v /etc/localtime:/etc/localtime:ro \
           -v ${SQUEEZE_DATA}:/srv/squeezebox \
           -v ${MUSIC_DIR}:/srv/music \
           ${IMG_NAME}

